FROM nginx:stable-alpine
EXPOSE 80 443

COPY nginx.conf /etc/nginx/nginx.conf
COPY ./certificate /etc/nginx/ssl

# sudo docker run --network=host patanindev/pocnginx 
# network mode host work only on linux